import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
    // backgroundColor: '#F6F6F6',
    backgroundColor: '#fff',
  },
  button: {
    backgroundColor: '#20B08E',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 35,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: 'white',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: '600',
    color: 'black',
    letterSpacing: 1,
  },
  bottomContainer: {
    justifyContent: 'center',
    height: height / 3,
  },
  textInput: {
    height: 40,
    borderWidth: 1,
    borderColor: '#20B08E',
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 25,
    paddingLeft: 10,
    color: 'black',
    textAlign: 'center',
    backgroundColor: '#010101',
  },
  textInputForm: {
    height: 40,
    borderWidth: 1,
    borderColor: '#20B08E',
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 25,
    paddingLeft: 10,
    color: 'white',
    textAlign: 'center',
    backgroundColor: '#010101',
  },
  formButton: {
    backgroundColor: '#20B08E',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 35,
    marginHorizontal: 20,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  formInputContainer: {
    // marginBottom: 20,
    marginTop: 20,
    ...StyleSheet.absoluteFill,
    zIndex: -1,
    justifyContent: 'center',
  },
  closeButtonContainer: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 1,
    backgroundColor: '#010101',
    alignItems: 'center',
    borderRadius: 20,
    top: -20,
  },
  activityIndicatorContainer: {
    ...StyleSheet.absoluteFill,
    zIndex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },

  postContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 4,
    marginRight: 10,
    marginLeft: 10,
    marginTop: 10,
  },
  postHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  postAuthor: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#000',
  },
  postDate: {
    color: '#888',
    fontSize: 12,
  },
  postBody: {
    marginBottom: 8,
  },
  postTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 4,
    marginRight: 10,
    color: '#000',
  },
  postContent: {
    color: '#888',
    fontSize: 14,
  },
  postFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  postLikes: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  postLikesCount: {
    // marginLeft: 4,
    fontSize: 14,
    color: '#888',
  },
  postComments: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 20,
  },

  postCommentsCount: {
    marginLeft: 4,
    fontSize: 14,
    color: '#888',
  },
  postImage: {
    width: '100%',
    height: 200,
    opacity: 0.9,
    borderRadius: 10,
  },
  postLoading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postLoadingText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#888',
  },
  postScreenContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 10,
    marginTop: 20,
  },
  postFooter: {
    flexDirection: 'row',
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
    // backgroundColor: '#242424',
  },
  postCommentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  postCommentsText: {
    color: '#20B08E',
    marginLeft: 5,
  },
  postCreatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
  },
  postCreator: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  postCommentsContainer: {
    width: '100%',
    height: '100%',
    marginBottom: 10,
    marginTop: 20,
  },
  postCommentItemContainer: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    marginVertical: 5,
    marginHorizontal: 10,
  },
  postCommentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  postCommentLine: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    marginTop: 10,
    marginBottom: 10,
  },
  postTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    color: '#20B08E',
  },
  postTag: {
    color: '#20B08E',
    marginRight: 5,
    marginBottom: 5,
  },
  postDescription: {
    color: '#000',
    fontSize: 14,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
  },
});

export default styles;
